; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{453EA5D4-BCF4-4E04-BE8C-EBBD5BEA1056}
AppName=Stick Royale_DEMO
AppVersion=1
;AppVerName=Stick Royale_DEMO 1
AppPublisher=Triplefin Games
AppPublisherURL=https://stickroyalegame.com/
AppSupportURL=https://stickroyalegame.com/
AppUpdatesURL=https://stickroyalegame.com/
DefaultDirName={pf}\Stick_Royale_DEMO
DisableProgramGroupPage=yes
OutputBaseFilename=setup_STICKROYALEDEMO
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\User\Projects\StickRoyale\afunroyalegame\afunroyalegame_main\Builds\Stick Royale.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Projects\StickRoyale\afunroyalegame\afunroyalegame_main\Builds\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\Stick Royale_DEMO"; Filename: "{app}\Stick Royale.exe"
Name: "{commondesktop}\Stick Royale_DEMO"; Filename: "{app}\Stick Royale.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\Stick Royale.exe"; Description: "{cm:LaunchProgram,Stick Royale_DEMO}"; Flags: nowait postinstall skipifsilent

